feat: create custom 404 page
non-profit-dev/sterczace-uszy pull request #243
Opened 2024-01-29 17:22 UTC by AmandaKr

## Description 📝

This PR introduces Custom 404 Page.

## Related Issues 🔗

JIRA issue: [FSU-413](https://klau.atlassian.net/browse/FSU-413)

## Resources 📚

## Preview Links 🔍

## Ask for Help 🙋‍♀️🙋‍♂️

2024-02-03 13:13 UTC, imklau requested changes
code changes look good, just the missing container for the content 👀 

![Zrzut ekranu 2024-02-3 o 14 12 35](https://github.com/non-profit-dev/sterczace-uszy/assets/23500678/89e2acfc-a170-417c-9dc5-51729f553e92)

2024-02-08 11:05 UTC, imklau commented on packages/frontend/app/templates/PageNotFound/PageNotFound.jsx
> +        subtitle="Ups..coś poszło nie tak"
```suggestion
        subtitle="Ups...coś poszło nie tak"
```
missing dot 😅

2024-02-08 11:05 UTC, imklau approved these changes

2024-02-10 09:42 UTC, imklau commented on packages/frontend/app/templates/PageNotFound/PageNotFound.jsx
> +        subtitle="Ups...coś poszło nie tak"
```suggestion
        subtitle="Ups, coś poszło nie tak"
```

2024-02-12 09:51 UTC, agnieszkastanczuk approved these changes

2024-02-12 18:08 UTC, merged